export default [
    {
        number: 1234433,
        name: 'Vacancy test',
        city: 'Hadera',
        wagePerHour: 39,
        workingHoursStart: 8,
        workingHoursEnd: 12,
        driver: true,
        morningShift: '8:00-12:00',
        nightShift: '20:00-0:00',
        workBreak: '1 Час',
        lunch: false,
        living: true,
        bonuses: false,
        additionalInfo: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsa neque quo, reprehenderit esse explicabo nulla vero, rerum eius aut deserunt nemo exercitationem enim voluptatibus vitae consectetur sit cum numquam perspiciatis!'
    },
    {
        number: 1234433,
        name: 'Vacancy test',
        city: 'Hadera',
        wagePerHour: 39,
        workingHoursStart: 8,
        workingHoursEnd: 12,
        driver: true,
        morningShift: '8:00-12:00',
        nightShift: '20:00-0:00',
        workBreak: '1 Час',
        lunch: false,
        living: true,
        bonuses: false,
        additionalInfo: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsa neque quo, reprehenderit esse explicabo nulla vero, rerum eius aut deserunt nemo exercitationem enim voluptatibus vitae consectetur sit cum numquam perspiciatis!'
    },
    {
        number: 1234430,
        name: 'Vacancy test 2',
        city: 'Hadera',
        wagePerHour: 44,
        workingHoursStart: 8,
        workingHoursEnd: 12,
        driver: true,
        morningShift: '8:00-12:00',
        nightShift: '21:00-0:00',
        workBreak: '1 Час',
        lunch: false,
        living: true,
        bonuses: false,
        additionalInfo: 'booooooooo'
    },
    {
        number: 1234400,
        name: 'Netflix content manager',
        city: 'Tel Aviv',
        wagePerHour: 77,
        workingHoursStart: 8,
        workingHoursEnd: 15,
        driver: true,
        morningShift: '8:00-14:00',
        nightShift: '20:00-0:00',
        workBreak: '2 h',
        lunch: false,
        living: false,
        bonuses: false,
        additionalInfo: 'oh my god cool work'
    },
];